export const STRINGS = {
  title: 'SWING SALVAGE',
  dragToStart: 'Drag anywhere to start',
  dragToFly: 'Drag anywhere to fly',
  hookIt: 'Hook it!',
  setGently: 'Set it down gently',
  best: 'BEST',
  score: 'SCORE',
  daily: 'DAILY',
  shipProgress: 'SHIP {n} · {k}/{q}',
  perfect: 'PERFECT',
  steady: 'STEADY HANDS!',
  shipFull: 'SHIP FULL',
  splashTitle: 'SPLASH!',
  splashSub: 'Cargo lost at sea',
  crashTitle: 'CRASH!',
  crashSub: 'Watch the ship!',
  toppleTitle: 'TOPPLED!',
  toppleSub: 'Your stack fell over',
  newBest: 'NEW BEST!',
  soClose: 'So close! {n} away from your best',
  unlockProgress: '{n} more crates to unlock {paint}',
  newPaint: 'New paint unlocked: {paint}!',
  firstMedal: 'First {medal} medal!',
  delivered: 'Crates delivered: {n}',
  xpToRank: '{n} XP to rank {rank}',
  again: 'AGAIN',
  playNormal: 'PLAY NORMAL',
  secondChance: 'SECOND CHANCE',
  watchAd: 'watch an ad',
  share: 'SHARE',
  home: 'HOME',
  copied: 'Copied!',
  paused: 'PAUSED',
  resume: 'RESUME',
  hangar: 'HANGAR',
  settings: 'SETTINGS',
  back: 'BACK',
  selected: 'SELECTED',
  tapToUse: 'TAP TO USE',
  sound: 'Sound',
  haptics: 'Haptics',
  privacy: 'Privacy options',
  howToPlay: 'How to play',
  privacyPolicy: 'Privacy policy',
  triesLeft: '{n} tries left today',
  dailyTag: 'DAILY #{n}',
  dailyBtn: '#{n} · {k} left',
  rewards: {
    flawless: 'FLAWLESS', perfect: 'PERFECT', chain: 'CHAIN', swing: 'SWING', closeCall: 'CLOSE CALL',
    gustHook: 'STORM HOOK', gustLanding: 'GUSTY DROP', saved: 'SAVED!', speedy: 'SPEEDY', sweet: 'SWEET SPOT', clean: 'CLEAN',
    snap: 'ROPE SNAP!',
  },
  combo: 'COMBO',
  storm: 'STORM',
  ghost: 'GHOST',
  wind: 'WIND',
  medals: { bronze: 'BRONZE', silver: 'SILVER', gold: 'GOLD', platinum: 'PLATINUM' },
  paints: {
    rescue: 'RESCUE RED',
    sunny: 'SUNNY',
    mint: 'MINT',
    navy: 'NAVY',
    paper: 'PAPER',
    gold: 'GOLD',
    coral: 'CORAL',
    lavender: 'LAVENDER',
    teal: 'TEAL',
    charcoal: 'CHARCOAL',
    tangerine: 'TANGERINE',
    candy: 'CANDY',
    midnight: 'MIDNIGHT',
    aurora: 'AURORA',
  },
} as const;

/** `{n}` gibi yer tutucuları doldurur. */
export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? `{${k}}`));
}
